<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'dropdown-menu', $columnsLimit) ?>

<hr>

<nav class="navbar navbar-default" role="navigation">

    <ul class="nav navbar-nav">
      <li><a href="#">aimbientes</a></li>
      <li><a href="#">produtos</a></li>
      <li><a href="#">campanhas</a></li>
      <li><a href="#">próximas campanhas</a></li>
    </ul>

    <form class="navbar-form navbar-right" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
    </form>

</div>
